version: '3.8'

services:
  web:
    build: ./app
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    deploy:
      replicas: 3

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
